name: PR-pipeline_graph-autofusion

concurrency:
  max: 5
  exceed-action: QUEUE
  enable: true
  preemption:
    enable: true
    events: [mr_id]

on:
  pr_comment:
      types: [ created ]
      keyword: '^(?:\/)?compile*'
  pull_request_comment:
    types: [created]
    branches: [ '*' ]
    comments: [ '^(?:\/)?compile*' ]

env:
  org_name: "cann"
  repo_name: "graph-autofusion"
  MERGE_ID: ${{atomgit.event.pull_request.number}}
  TARGET_BRANCH: ${{atomgit.base_ref}}
  SOURCE_BRANCH: ${{atomgit.head_ref}}
  obs_path: "${{ vars.OBS_PATH }}/${{ env.MERGE_ID }}"
  obs_smoke_path: "${{ env.obs_path }}/presmoke/2"

stages:
  stage1:
    name: image
    jobs:
      JOB_image:
        name: Test_image
        steps:
          - name: revise_image
            identifier: revise_image
            uses: cann/.gitcode/actions/revise-img@master
            with:
              repo_name: "graph-autofusion"
              target_branch: ${{ env.TARGET_BRANCH }}
              repo_url: ${{ vars.CI_PATH }}
          -
            name: show_output
            run: |
              echo "image: ${{ steps.revise_image.outputs.Compile_Ascend_X86 }}"
        if: "${{ default() }}"
        runs-on: [dedicate-hosted, x64, small]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
      JOB_pr:
        name: Test_get-pr
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
              token: ${{secrets.GIT_TOKEN}}
          -
            name: get_pr
            identifier: get_pr
            uses: cann/.gitcode/actions/get-pr@master
            with:
              workspace: ${{ steps.process_checkout.outputs.path }}
              target_branch: ${{ env.TARGET_BRANCH }}
              git_token: ${{secrets.GIT_TOKEN}}
          -
            name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{secrets.AK}}
              secret-key: ${{secrets.SK}}
              artifact-path: |
                ${{ steps.process_checkout.outputs.path }}/pr_filelist.txt
                ${{ steps.process_checkout.outputs.path }}/pr_filelist_mod.txt
                ${{ steps.process_checkout.outputs.path }}/pr_filelist_precommit.txt
                ${{ steps.process_checkout.outputs.path }}/update_file_detail.txt
              object-prefix: ${{ env.obs_path }}/
        runs-on:
        - default
      JOB_shell:
        name: Test_get-shell
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: master
              token: ${{secrets.GIT_TOKEN}}
          -
            name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{secrets.AK}}
              secret-key: ${{secrets.SK}}
              artifact-path: |
                ${{ steps.process_checkout.outputs.path }}/.gitcode/scripts/*
              object-prefix: ${{ env.obs_path }}/
        if: "${{ default() }}"
        runs-on:
        - default
    pre:
    - type: auto
    fail-fast: true
  stage2:
    name: compile
    jobs:
      JOB_codecheck_action:
        name: CodeCheck
        uses: .gitcode/workflows/codecheck_action.yml
        with:
          precommit_image_version: ${{ jobs.JOB_image.outputs.precommit }}
          codecheck_image_version: ${{ jobs.JOB_image.outputs.codecheck }}
      JOB_x86_compile:
        name: Compile_Ascend_X86
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_X86'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86 }}
          arch: 'x64'
          package_name: 'cann-graph-autofusion_linux-x86_64.run'
      JOB_x86_compile_ubuntu24:
        name: Compile_Ascend_X86_ubuntu24
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_X86_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86_ubuntu24 }}
          arch: 'x64'
          package_name: 'cann-graph-autofusion_linux-x86_64_ubuntu24.run'
      JOB_arm_compile:
        name: Compile_Ascend_ARM
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM }}
          arch: 'arm64'
          package_name: 'cann-graph-autofusion_linux-aarch64.run'
      JOB_arm_compile_ubuntu24:
        name: Compile_Ascend_ARM_ubuntu24
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'Compile_Ascend_ARM_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM_ubuntu24 }}
          arch: 'arm64'
          package_name: 'cann-graph-autofusion_linux-aarch64_ubuntu24.run'
      JOB_staticcheck_markdown:
        name: CodeCheck_staticcheck_markdown
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'markdown'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
      JOB_staticcheck_codespell_check:
        name: CodeCheck_staticcheck_codespell_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'codespell_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
      JOB_staticcheck_tag_closed_check:
        name: CodeCheck_staticcheck_tag_closed_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'tag_closed_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
      JOB_staticcheck_resource_existence_check:
        name: CodeCheck_staticcheck_resource_existence_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'resource_existence_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
      JOB_staticcheck_link_validity_check:
        name: CodeCheck_staticcheck_link_validity_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'link_validity_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
    pre:
    - type: auto
    fail-fast: false
  stage3:
    name: ut
    select: selected_by_default
    jobs:
      JOB_api_check:
        name: API_Check
        select: selected_by_default
        needs: []
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
              token: ${{secrets.GIT_TOKEN}}
          -
            name: api_check
            identifier: api_check
            uses: cann/.gitcode/actions/api-check@master
            with:
              org_name: ${{ env.org_name }}
              mode: "check"
              repo_name: ${{ env.repo_name }}
              source_branch: ${{ env.SOURCE_BRANCH }}
              target_branch: ${{ env.TARGET_BRANCH }}
              merge_id: ${{ env.MERGE_ID }}
              WORKSPACE: ${{ steps.process_checkout.outputs.path }}
        if: "${{ default() }}"
        runs-on: [dedicated-hosted, x64, large]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ jobs.JOB_image.outputs.codecheck }}
      JOB_UT_TEST_Python_superkernel:
        name: UT_Test_Python_superkernel
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'UT_Test_Python_superkernel'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test_Python_superkenel }}
      JOB_ST_TEST_Python_superkernel:
        name: ST_Test_Python_superkernel
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'ST_Test_Python_superkernel'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.ST_Test_Python_superkenel }}
      JOB_UT_TEST_superkernel:
        name: UT_Test_superkernel
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'UT_Test_superkernel'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test_superkernel }}
      JOB_UT_TEST_autofuse_framework:
        name: UT_Test_autofuse_framework
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'UT_Test_autofuse_framework'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test_autofuse_framework }}
      JOB_ST_TEST_autofuse_framework:
        name: ST_Test_autofuse_framework
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'ST_Test_autofuse_framework'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.ST_Test_autofuse_framework }}
      JOB_UT_TEST_autofuse_ascendc_api:
        name: UT_Test_autofuse_ascendc_api
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'UT_Test_autofuse_ascendc_api'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test_autofuse_ascendc_api }}
      JOB_ST_TEST_autofuse_ascendc_api:
        name: ST_Test_autofuse_ascendc_api
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'ST_Test_autofuse_ascendc_api'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.ST_Test_autofuse_ascendc_api }}
      JOB_ST_TEST_autofuse_e2e:
        name: ST_Test_autofuse_e2e
        select: selected_by_default
        needs: []
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'ST_Test_autofuse_e2e'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.ST_Test_autofuse_e2e }}
    pre:
    - type: auto
    fail-fast: false
  stage4:
    name: PreSmoke
    jobs:
      A2_smoke:
        name: PreSmoke_A2
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              token: ${{secrets.GIT_TOKEN}}
              path: "./runner"
          -
            name: Checkout gitcode
            identifier: process_checkout_gitcode
            uses: checkout
            with:
              repository: "https://gitcode.com/cann/.gitcode.git"
              ref: master
              path: "./runner/ci"
          -
            name: download
            uses: obs-download
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{ secrets.AK }}
              secret-key: ${{ secrets.SK }}
              key: |
                ${{ env.obs_path }}/pr_filelist.txt
                ${{ env.obs_path }}/pr_filelist_mod.txt
                ${{ env.obs_path }}/update_file_detail.txt
                ${{ env.obs_path }}/pre_smoke.sh
              path: ${{ steps.process_checkout.outputs.path }}
          -
            name: tar businesscode
            run: |
              cd ${{ steps.process_checkout.outputs.path }}
              tar -zcf ../smoke_data.tar.gz .
              mv ../smoke_data.tar.gz ./
          -
            name: upload
            identifier: process_upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{secrets.AK}}
              secret-key: ${{secrets.SK}}
              artifact-path: |
                ${{ steps.process_checkout.outputs.path }}/smoke_data.tar.gz
              object-prefix: ${{ env.obs_smoke_path }}/
          -
            name: smoke executor
            uses: manifest-management-plugin
            with:
              action: DEPLOY
              repo: ${{ steps.process_checkout.outputs.path }}
              file_path: ${{ steps.process_checkout.outputs.path }}/ci/smoke-conf/smoke-A2.yaml
              manifest_image: swr.cn-south-1.myhuaweicloud.com/pre_smoke/${{ jobs.JOB_image.outputs.PreSmoke_A900_npupool }}
              custom_shell_script: |-
                set -e
                # set env
                export repo_name=${{env.repo_name}}
                export pr_id=${{ env.MERGE_ID }}
                export AK=${{secrets.AK}}
                export SK=${{secrets.SK}}
                export obs_smoke_path=${{ env.obs_smoke_path }}
                export obs_path=${{ env.obs_path }}
                export arm_run_url=${{jobs.JOB_arm_compile_ubuntu24.outputs.arm_run_url}}
                mkdir -p /home/taskspace && cd /home/taskspace
                wget -nv ${{ steps.process_upload.outputs.primary-url }}
                tar -zxf $(basename "${{ steps.process_upload.outputs.primary-url }}")
                bash /home/taskspace/pre_smoke.sh
          -
            name: smoke resource clean
            uses: manifest-management-plugin
            with:
              action: CRUSH
              repo: ${{ steps.process_checkout.outputs.path }}
              file_path: ${{ steps.process_checkout.outputs.path }}/ci/smoke-conf/smoke-A2.yaml
        if: "${{ default() }}"
        runs-on: ['self-hosted','arch=arm','smoke=204']
    pre:
    - type: auto
    fail-fast: true
