/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

// CPU-sim harness for the AFIR-generated 3D LoadAddStore kernel.
//   out = in0 + in1, <100x16x8xf16> flattened to 12800 elems.
// The kernel body is textually included from kbody.inc (generated by
// af-opt --convert-afir-to-ascendc-queue | ascir-translate -mlir-to-ascendc).
#include "kernel_operator.h"

struct TilingData {
  int64_t tile_len;
  int64_t total;
};

#include "kbody.inc"
#include "af_kfunc.h"  // generated by reproduce.sh: #define AF_KERNEL_FUNC <entry>

#include "tikicpulib.h"
#include "kern_fwk.h"
#include <cstdio>
#include <cmath>
#include <cstdlib>

int main(int argc, char **argv) {
  constexpr int TILE_LEN = 256;
  int TOTAL = (argc > 1) ? atoi(argv[1]) : 12800;
  size_t b = TOTAL * sizeof(half);
  half *x = (half *)AscendC::GmAlloc(b);
  half *y = (half *)AscendC::GmAlloc(b);
  half *o = (half *)AscendC::GmAlloc(b);
  uint8_t *ws = (uint8_t *)AscendC::GmAlloc(1024);
  for (int i = 0; i < TOTAL; ++i) {
    x[i] = (half)((float)(i % 64) * 0.5f);
    y[i] = (half)((float)(i % 32) * 0.25f);
    o[i] = (half)-1.0f;
  }
  TilingData t{TILE_LEN, TOTAL};
  ICPU_RUN_KF(LoadAddStore_0_B0Y3_S0G0C0, 1, x, y, o, ws, t);
  fflush(stdout);

  int e = 0;
  for (int i = 0; i < TOTAL; ++i) {
    float g = (float)o[i];
    float ex = (float)(i % 64) * 0.5f + (float)(i % 32) * 0.25f;
    if (std::fabs(g - ex) >= 1e-2f) {
      if (e < 8) fprintf(stderr, "  bad[%d] got=%f exp=%f\n", i, g, ex);
      e++;
    }
  }
  fprintf(stderr, "[VERIFY] out[0]=%.3f out[255]=%.3f out[12799]=%.3f\n", (float)o[0], (float)o[255], (float)o[12799]);
  fprintf(stderr, e ? "[RESULT] FAIL %d/%d mismatches\n" : "[RESULT] PASS all %d elements (out = in0 + in1)\n",
          e ? e : TOTAL, TOTAL);
  return e ? 1 : 0;
}
