/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

// Real-NPU launcher for 3D LoadAddStore <100x16x8xf16>
// Total: 100*16*8 = 12800 elements, tile_len: 256
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <vector>
#include <dlfcn.h>

#include "af_kfunc.h"  // generated by reproduce.sh: #define AF_KERNEL_FUNC <entry>
#define AF_STR2(x) #x
#define AF_STR(x) AF_STR2(x)  // stringize the kernel-entry token for rtFunctionRegister

struct DevBinary {
  uint32_t magic;
  uint32_t version;
  const char *data;
  uint64_t length;
};
static constexpr uint32_t kMagicElfAiVec = 0x41415246u;

#ifdef AF_REAL_NPU
extern "C" int aclInit(const char *);
extern "C" int aclrtSetDevice(int);
#endif

using FnSetDevice = int (*)(int32_t);
using FnStreamCreate = int (*)(void **, int32_t);
using FnStreamSynchronize = int (*)(void *);
using FnMalloc = int (*)(void **, uint64_t, int32_t, uint16_t);
using FnMemcpy = int (*)(void *, uint64_t, const void *, uint64_t, int32_t);
using FnDevBinaryRegister = int (*)(const DevBinary *, void **);
using FnFunctionRegister = int (*)(void *, const void *, const char *, const void *, uint32_t);
using FnKernelLaunch = int (*)(const void *, uint32_t, void *, uint32_t, void *, void *);

struct RuntimeFunctions {
  FnSetDevice setDevice;
  FnStreamCreate streamCreate;
  FnStreamSynchronize streamSynchronize;
  FnMalloc malloc;
  FnMemcpy memoryCopy;
  FnDevBinaryRegister devBinaryRegister;
  FnFunctionRegister functionRegister;
  FnKernelLaunch kernelLaunch;
};

template <typename Function>
bool loadSymbol(void *runtime, const char *name, Function &function) {
  function = reinterpret_cast<Function>(dlsym(runtime, name));
  if (function) return true;
  printf("dlsym %s failed: %s\n", name, dlerror());
  return false;
}

bool loadRuntimeFunctions(void *runtime, RuntimeFunctions &functions) {
  if (!loadSymbol(runtime, "rtSetDevice", functions.setDevice)) return false;
  if (!loadSymbol(runtime, "rtStreamCreate", functions.streamCreate)) return false;
  if (!loadSymbol(runtime, "rtStreamSynchronize", functions.streamSynchronize)) return false;
  if (!loadSymbol(runtime, "rtMalloc", functions.malloc)) return false;
  if (!loadSymbol(runtime,
                  "rtMem"
                  "cpy",
                  functions.memoryCopy))
    return false;
  if (!loadSymbol(runtime, "rtDevBinaryRegister", functions.devBinaryRegister)) return false;
  if (!loadSymbol(runtime, "rtFunctionRegister", functions.functionRegister)) return false;
  return loadSymbol(runtime, "rtKernelLaunch", functions.kernelLaunch);
}

static std::vector<uint8_t> readFile(const char *p) {
  FILE *f = fopen(p, "rb");
  if (!f) return {};
  fseek(f, 0, SEEK_END);
  long n = ftell(f);
  fseek(f, 0, SEEK_SET);
  std::vector<uint8_t> b(n);
  size_t rd = fread(b.data(), 1, n, f);
  (void)rd;
  fclose(f);
  return b;
}

template <typename To, typename From>
To copyObjectBits(const From &source) {
  static_assert(sizeof(To) == sizeof(From), "bit copy requires equal-sized types");
  To result{};
  const auto *sourceBytes = reinterpret_cast<const unsigned char *>(&source);
  auto *resultBytes = reinterpret_cast<unsigned char *>(&result);
  std::copy_n(sourceBytes, sizeof(source), resultBytes);
  return result;
}

// f32 <-> f16 conversion (IEEE 754 half). Needed for CORRECT verification:
// storing an int as raw f16 bits and comparing bits to 3*i only works below
// 2048 (denormal + exp=1 range where bits==value); above that f16 step size
// grows, so we must use real float values + tolerance.
static uint16_t toHalf(float f) {
  uint32_t x = copyObjectBits<uint32_t>(f);
  uint32_t sign = (x >> 16) & 0x8000;
  int32_t exp = ((x >> 23) & 0xff) - 127 + 15;
  uint32_t man = (x >> 13) & 0x3ff;
  if (exp <= 0) return (uint16_t)sign;
  if (exp >= 0x1f) return (uint16_t)(sign | 0x7c00);
  return (uint16_t)(sign | (exp << 10) | man);
}
static float toF32(uint16_t h) {
  uint32_t sign = (h & 0x8000) << 16;
  int32_t exp = (h >> 10) & 0x1f;
  uint32_t man = (h & 0x3ff);
  if (exp == 0) return sign ? -0.0f : 0.0f;
  uint32_t f = sign | ((exp - 15 + 127) << 23) | (man << 13);
  return copyObjectBits<float>(f);
}

struct HostData {
  std::vector<uint16_t> input0;
  std::vector<uint16_t> input1;
  std::vector<uint16_t> output;
  std::vector<float> floatInput0;
  std::vector<float> floatInput1;
};

HostData makeHostData(int size) {
  HostData data{{}, {}, {}, {}, {}};
  data.input0.resize(size);
  data.input1.resize(size);
  data.output.resize(size);
  data.floatInput0.resize(size);
  data.floatInput1.resize(size);
  for (int i = 0; i < size; ++i) {
    data.floatInput0[i] = (i % 64) * 0.5f;
    data.floatInput1[i] = (i % 32) * 0.25f;
    data.input0[i] = toHalf(data.floatInput0[i]);
    data.input1[i] = toHalf(data.floatInput1[i]);
  }
  return data;
}

struct RunContext {
  const RuntimeFunctions &runtime;
  const char *functionName;
  void *stream;
  void *deviceInput0;
  void *deviceInput1;
  void *deviceOutput;
  HostData &host;
};

struct ExecutionState {
  void *library = nullptr;
  RuntimeFunctions runtime{};
  void *stream = nullptr;
  std::vector<uint8_t> kernelBinary;
  void *module = nullptr;
  void *deviceInput0 = nullptr;
  void *deviceInput1 = nullptr;
  void *deviceOutput = nullptr;
  HostData host;
};

bool openRuntime(int argc, char **argv, ExecutionState &state) {
  printf("==================== [1] locate real libruntime ====================\n");
  const char *runtimePath = argc > 1 ? argv[1] : "/usr/local/Ascend/cann-8.5.1/aarch64-linux/lib64/libruntime.so";
  state.library = dlopen(runtimePath, RTLD_NOW);
  if (!state.library) {
    printf("dlopen runtime: %s\n", dlerror());
    return false;
  }
  printf("runtime lib: %s\n", runtimePath);
#ifdef AF_REAL_NPU
  printf("aclInit rc=%d\n", aclInit(nullptr));
  printf("aclrtSetDevice(5) rc=%d\n", aclrtSetDevice(5));
#endif
  if (!loadRuntimeFunctions(state.library, state.runtime)) return false;
#ifndef AF_REAL_NPU
  printf("rtSetDevice(0) rc=%d\n", state.runtime.setDevice(0));
#endif
  return true;
}

bool registerKernel(ExecutionState &state, const char *functionName) {
  printf("==================== [3] run (device: real=5 / camodel=0) ====================\n");
  int rc = state.runtime.streamCreate(&state.stream, 0);
  printf("rtStreamCreate rc=%d\n", rc);
  state.kernelBinary = readFile("kernel.bin");
  if (state.kernelBinary.empty()) {
    printf("kernel.bin not found\n");
    return false;
  }
  DevBinary binary{kMagicElfAiVec, 0, reinterpret_cast<const char *>(state.kernelBinary.data()),
                   state.kernelBinary.size()};
  rc = state.runtime.devBinaryRegister(&binary, &state.module);
  printf("rtDevBinaryRegister rc=%d\n", rc);
  rc = state.runtime.functionRegister(state.module, reinterpret_cast<const void *>(functionName), functionName,
                                      reinterpret_cast<const void *>(functionName), 0);
  printf("rtFunctionRegister rc=%d\n", rc);
  return rc == 0;
}

void prepareBuffers(ExecutionState &state, int maxElements) {
  const size_t maxBytes = static_cast<size_t>(maxElements) * sizeof(uint16_t);
  state.runtime.malloc(&state.deviceInput0, maxBytes, 0, 0);
  state.runtime.malloc(&state.deviceInput1, maxBytes, 0, 0);
  state.runtime.malloc(&state.deviceOutput, maxBytes, 0, 0);
  state.host = makeHostData(maxElements);
  state.runtime.memoryCopy(state.deviceInput0, maxBytes, state.host.input0.data(), maxBytes, 1);
  state.runtime.memoryCopy(state.deviceInput1, maxBytes, state.host.input1.data(), maxBytes, 1);
}

bool runCase(RunContext &context, int total, uint32_t blockDim, int tileLen) {
  if (tileLen == 0) {
    printf("  invalid tileLen=%d\n", tileLen);
    return false;
  }
  if (tileLen < 0) {
    printf("  invalid tileLen=%d\n", tileLen);
    return false;
  }
  const int tail = total % tileLen;
  const size_t bytes = static_cast<size_t>(total) * sizeof(uint16_t);
  std::vector<uint16_t> zero(total, 0);
  context.runtime.memoryCopy(context.deviceOutput, bytes, zero.data(), bytes, 1);

  struct {
    void *p[4];
    int64_t tile_len;
    int64_t total;
  } args{{context.deviceInput0, context.deviceInput1, context.deviceOutput, nullptr}, tileLen, total};

  int rc = context.runtime.kernelLaunch(reinterpret_cast<const void *>(context.functionName), blockDim, &args,
                                        sizeof(args), nullptr, context.stream);
  rc |= context.runtime.streamSynchronize(context.stream);
  context.runtime.memoryCopy(context.host.output.data(), bytes, context.deviceOutput, bytes, 2);

  int errors = 0;
  for (int i = 0; i < total; ++i) {
    float expected = context.host.floatInput0[i] + context.host.floatInput1[i];
    if (std::fabs(toF32(context.host.output[i]) - expected) >= 1e-2f) ++errors;
  }
  const bool passed = rc == 0 && errors == 0;
  printf("  total=%-5d tail=%-3d blockDim=%d  launch_rc=%d errors=%d/%d -> %s\n", total, tail, blockDim, rc, errors,
         total, passed ? "PASS" : "FAIL");
  return passed;
}

bool runCases(RunContext &context, int tileLen) {
  const int totals[] = {12800, 12808, 12840};
  const uint32_t blockDims[] = {1, 2, 8};
  bool allPassed = true;
  for (int total : totals) {
    for (uint32_t blockDim : blockDims) allPassed &= runCase(context, total, blockDim, tileLen);
  }
  return allPassed;
}

int main(int argc, char **argv) {
  constexpr int TILE_LEN = 256;  // 512B/tile, 32B-aligned
  constexpr int MAXN = 12840;    // max total across runs
  printf("==================== [2] compile launcher (real NPU: -DAF_REAL_NPU + link ACL) ====================\n");
  printf("launcher built OK\n");
  const char *func_name = AF_STR(AF_KERNEL_FUNC);
  ExecutionState state;
  if (!openRuntime(argc, argv, state) || !registerKernel(state, func_name)) return 1;
  prepareBuffers(state, MAXN);
  printf("==================== [6] verify: same kernel, varied total x blockDim ====================\n");
  RunContext context{state.runtime,      func_name,          state.stream, state.deviceInput0,
                     state.deviceInput1, state.deviceOutput, state.host};
  bool allPass = runCases(context, TILE_LEN);

  printf("==================== %s ====================\n",
         allPass ? "ALL PASS (one kernel: 3 totals x 3 blockDims, tail + multi-core)" : "FAIL");
  return allPass ? 0 : 1;
}
