/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of 
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, 
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#ifndef AF_INC_GRAPH_ATTR_GROUP_ATTR_GROUP_BASE_H
#define AF_INC_GRAPH_ATTR_GROUP_ATTR_GROUP_BASE_H

#include <memory>
#include "graph/ge_error_codes.h"
#include "graph/type_utils.h"

namespace af {
namespace proto {
class AttrGroupDef;
class AttrGroups;
class ShapeEnvAttrGroupsDef;
class AfAttrGroupsDef;
}  // namespace proto
}  // namespace af

#ifdef AUTOFUSE_USE_GE_METADEF
#include "graph/attribute_group/attr_group_base.h"

namespace af {
using ge::TypeId;
using ge::graphStatus;
using AttrHolder = ::ge::AttrHolder;

class AttrGroupsBase : public ::ge::AttrGroupsBase {
 public:
  AttrGroupsBase() = default;
  ~AttrGroupsBase() override = default;

  graphStatus Serialize(::ge::proto::AttrGroupDef &attr_group_def) final {
    (void) attr_group_def;
    return ge::GRAPH_FAILED;
  }
  graphStatus Deserialize(const ::ge::proto::AttrGroupDef &attr_group_def, AttrHolder *attr_holder) final {
    (void) attr_group_def;
    (void) attr_holder;
    return ge::GRAPH_FAILED;
  }
  std::unique_ptr<::ge::AttrGroupsBase> Clone() final {
    auto cloned = CloneAf();
    return std::unique_ptr<::ge::AttrGroupsBase>(cloned.release());
  }

  virtual graphStatus Serialize(proto::AttrGroupDef &attr_group_def) {
    (void) attr_group_def;
    return ge::GRAPH_SUCCESS;
  }
  virtual graphStatus Deserialize(const proto::AttrGroupDef &attr_group_def, AttrHolder *attr_holder) {
    (void) attr_group_def;
    (void) attr_holder;
    return ge::GRAPH_SUCCESS;
  }
  virtual std::unique_ptr<AttrGroupsBase> CloneAf() = 0;
};

class AscTensorAttr;
class AscNodeAttr;
class AscGraphAttr;
class SymbolicDescAttr;
class ShapeEnvAttr;
class AutoFuseAttrs;
class AutoFuseGraphAttrs;
}  // namespace af

#else  // !AUTOFUSE_USE_GE_METADEF

// Forward declarations for proto types (in af::proto namespace, generated by protoc from package af.proto)
namespace af {
namespace proto {
class AttrGroupDef;
class AttrGroups;
class ShapeEnvAttrGroupsDef;
class AfAttrGroupsDef;
}  // namespace proto
}  // namespace af

// Forward declarations in namespace af for attr group classes defined there
namespace af {
class AscTensorAttr;
class AscNodeAttr;
class AscGraphAttr;
class SymbolicDescAttr;
class ShapeEnvAttr;
class AutoFuseAttrs;
class AutoFuseGraphAttrs;
}  // namespace af

namespace af {
using ge::TypeId;
using ge::graphStatus;
class AttrHolder;
class AttrGroupsBase {
 public:
  AttrGroupsBase() = default;

  virtual ~AttrGroupsBase() = default;
  virtual graphStatus Serialize(proto::AttrGroupDef &attr_group_def) {
    (void) attr_group_def;
    return ge::GRAPH_SUCCESS;
  }
  virtual graphStatus Deserialize(const proto::AttrGroupDef &attr_group_def, AttrHolder *attr_holder) {
    (void) attr_holder;
    (void) attr_group_def;
    return ge::GRAPH_SUCCESS;
  }
  virtual std::unique_ptr<AttrGroupsBase> CloneAf() = 0;
};

// typeid()方法存在bug，不同的类的typeid()可能相同，此处用模板特化一下，新增AttrGroupsBase子类属性组，需要实现这个方法，返回子类的typeid
// 前置声明子类，同时注意typeid不能与anchor冲突
class AscTensorAttr;
class AscNodeAttr;
class AscGraphAttr;
class SymbolicDescAttr;
class ShapeEnvAttr;
class AutoFuseAttrs;
class AutoFuseGraphAttrs;
} // namespace af

namespace ge {
template<>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::AttrGroupsBase>();

template<>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::AscTensorAttr>();

template<>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::AscNodeAttr>();

template<>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::AscGraphAttr>();

template<>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::SymbolicDescAttr>();

template<>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::ShapeEnvAttr>();

template <>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::AutoFuseAttrs>();

template <>
GE_FUNC_DEV_VISIBILITY GE_FUNC_HOST_VISIBILITY TypeId GetTypeId<af::AutoFuseGraphAttrs>();

} // namespace ge

#endif  // AUTOFUSE_USE_GE_METADEF

#endif // AF_INC_GRAPH_ATTR_GROUP_ATTR_GROUP_BASE_H
